spring.application.name=ProcessorMS

server.port=1013

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# another services
loader.service.url=${LOADER_URL:http://localhost:1010/api/loader}
metric.service.url=${METRIC_URL:http://localhost:1011/api/metric}
logger.service.url=${LOGGER_URL:http://localhost:1016/api/logger}

# swagger
springdoc.swagger-ui.path=/mst-processor-sw-ui
springdoc.api-docs.path=/mst-processor-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.document-title=Alert Hub - ProcessorMS

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true