spring.application.name=EvaluationMS
server.port=1090

spring.kafka.bootstrap-servers=localhost:9092

# Other services
loader.service.url=http://localhost:1010/api/loader

# Default email recipient for evaluation results
# You can change this later or pass email as request param
evaluation.notification.to=admin@gmail.com

# Swagger
springdoc.swagger-ui.path=/mst-evaluation-sw-ui
springdoc.api-docs.path=/mst-evaluation-api-docs
springdoc.swagger-ui.tryItOutEnabled=false