spring.application.name=EmailMS

server.port=1014

spring.kafka.bootstrap-servers=localhost:9092



# another services
logger.service.url=http://localhost:1016/api/logger


#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-email-sw-ui
# -YAML
springdoc.api-docs.path=/mst-email-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=false


spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
