spring.application.name=GatewayMS

server.port=1007

jwt.secret=AlertHubSecuritySecretKey19981998

spring.cloud.gateway.server.webflux.routes[0].id=security-ms
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:1008
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=CircuitBreaker=name=SecurityCB,fallbackUri=forward:/fallback/security

spring.cloud.gateway.server.webflux.routes[1].id=user-ms
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:1009
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**,/api/role/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=name=UserCB,fallbackUri=forward:/fallback/user

spring.cloud.gateway.server.webflux.routes[2].id=loader-ms
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:1010
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/loader/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=name=LoaderCB,fallbackUri=forward:/fallback/loader

spring.cloud.gateway.server.webflux.routes[3].id=metric-ms
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:1011
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/metric/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=CircuitBreaker=name=MetricCB,fallbackUri=forward:/fallback/metric

spring.cloud.gateway.server.webflux.routes[4].id=action-ms
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:1012
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/action/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=CircuitBreaker=name=ActionCB,fallbackUri=forward:/fallback/action

spring.cloud.gateway.server.webflux.routes[5].id=processor-ms
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:1013
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/processor/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=CircuitBreaker=name=ProcessorCB,fallbackUri=forward:/fallback/processor

spring.cloud.gateway.server.webflux.routes[6].id=email-ms
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:1014
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/email/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=CircuitBreaker=name=EmailCB,fallbackUri=forward:/fallback/email

spring.cloud.gateway.server.webflux.routes[7].id=sms-ms
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:1015
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/sms/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=CircuitBreaker=name=SmsCB,fallbackUri=forward:/fallback/sms

spring.cloud.gateway.server.webflux.routes[8].id=logger-ms
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:1016
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/logger/**
spring.cloud.gateway.server.webflux.routes[8].filters[0]=CircuitBreaker=name=LoggerCB,fallbackUri=forward:/fallback/logger

spring.cloud.gateway.server.webflux.routes[9].id=evaluation-ms
spring.cloud.gateway.server.webflux.routes[9].uri=http://localhost:1017
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/evaluation/**
spring.cloud.gateway.server.webflux.routes[9].filters[0]=CircuitBreaker=name=EvaluationCB,fallbackUri=forward:/fallback/evaluation


#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-gateway-sw-ui
# -YAML
springdoc.api-docs.path=/mst-gateway-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=true
#Change title web
springdoc.swagger-ui.document-title=Alert Hub - GatewayMS

springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.deepLinking=true
springdoc.api-docs.enabled=false