spring.application.name=GatewayMS

server.port=1007

jwt.secret=AlertHubSecuritySecretKey19981998

# ===============================
# Main MS Routes
# ===============================

spring.cloud.gateway.server.webflux.routes[0].id=security-ms
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:1008
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=CircuitBreaker=name=SecurityCB,fallbackUri=forward:/fallback/security

spring.cloud.gateway.server.webflux.routes[1].id=user-ms
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:1009
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**,/api/role/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=name=UserCB,fallbackUri=forward:/fallback/user

spring.cloud.gateway.server.webflux.routes[2].id=loader-ms
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:1010
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/loader/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=name=LoaderCB,fallbackUri=forward:/fallback/loader

spring.cloud.gateway.server.webflux.routes[3].id=metric-ms
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:1011
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/metric/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=CircuitBreaker=name=MetricCB,fallbackUri=forward:/fallback/metric

spring.cloud.gateway.server.webflux.routes[4].id=action-ms
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:1012
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/action/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=CircuitBreaker=name=ActionCB,fallbackUri=forward:/fallback/action

spring.cloud.gateway.server.webflux.routes[5].id=processor-ms
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:1013
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/processor/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=CircuitBreaker=name=ProcessorCB,fallbackUri=forward:/fallback/processor

spring.cloud.gateway.server.webflux.routes[6].id=email-ms
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:1014
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/email/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=CircuitBreaker=name=EmailCB,fallbackUri=forward:/fallback/email

spring.cloud.gateway.server.webflux.routes[7].id=sms-ms
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:1015
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/sms/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=CircuitBreaker=name=SmsCB,fallbackUri=forward:/fallback/sms

spring.cloud.gateway.server.webflux.routes[8].id=logger-ms
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:1016
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/logger/**
spring.cloud.gateway.server.webflux.routes[8].filters[0]=CircuitBreaker=name=LoggerCB,fallbackUri=forward:/fallback/logger

spring.cloud.gateway.server.webflux.routes[9].id=evaluation-ms
spring.cloud.gateway.server.webflux.routes[9].uri=http://localhost:1017
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/evaluation/**
spring.cloud.gateway.server.webflux.routes[9].filters[0]=CircuitBreaker=name=EvaluationCB,fallbackUri=forward:/fallback/evaluation


# ===============================
# Gateway Swagger UI
# ===============================

springdoc.swagger-ui.path=/mst-gateway-sw-ui
springdoc.api-docs.path=/mst-gateway-api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.document-title=Alert Hub - GatewayMS

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urlsPrimaryName=GatewayMS


# ===============================
# Swagger Dropdown List
# ===============================

springdoc.swagger-ui.urls[0].name=GatewayMS
springdoc.swagger-ui.urls[0].url=/mst-gateway-api-docs

springdoc.swagger-ui.urls[1].name=SecurityMS
springdoc.swagger-ui.urls[1].url=/mst-security-api-docs

springdoc.swagger-ui.urls[2].name=UserMS
springdoc.swagger-ui.urls[2].url=/mst-user-api-docs

springdoc.swagger-ui.urls[3].name=LoaderMS
springdoc.swagger-ui.urls[3].url=/mst-loader-api-docs

springdoc.swagger-ui.urls[4].name=MetricMS
springdoc.swagger-ui.urls[4].url=/mst-metric-api-docs

springdoc.swagger-ui.urls[5].name=ActionMS
springdoc.swagger-ui.urls[5].url=/mst-action-api-docs

springdoc.swagger-ui.urls[6].name=ProcessorMS
springdoc.swagger-ui.urls[6].url=/mst-processor-api-docs

springdoc.swagger-ui.urls[7].name=EmailMS
springdoc.swagger-ui.urls[7].url=/mst-email-api-docs

springdoc.swagger-ui.urls[8].name=SmsMS
springdoc.swagger-ui.urls[8].url=/mst-sms-api-docs

springdoc.swagger-ui.urls[9].name=LoggerMS
springdoc.swagger-ui.urls[9].url=/mst-logger-api-docs

springdoc.swagger-ui.urls[10].name=EvaluationMS
springdoc.swagger-ui.urls[10].url=/mst-evaluation-api-docs


# ===============================
# Swagger API Docs Routes
# ===============================

spring.cloud.gateway.server.webflux.routes[10].id=security-docs
spring.cloud.gateway.server.webflux.routes[10].uri=http://localhost:1008
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/mst-security-api-docs,/mst-security-api-docs/**

spring.cloud.gateway.server.webflux.routes[11].id=user-docs
spring.cloud.gateway.server.webflux.routes[11].uri=http://localhost:1009
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/mst-user-api-docs,/mst-user-api-docs/**

spring.cloud.gateway.server.webflux.routes[12].id=loader-docs
spring.cloud.gateway.server.webflux.routes[12].uri=http://localhost:1010
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/mst-loader-api-docs,/mst-loader-api-docs/**

spring.cloud.gateway.server.webflux.routes[13].id=metric-docs
spring.cloud.gateway.server.webflux.routes[13].uri=http://localhost:1011
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/mst-metric-api-docs,/mst-metric-api-docs/**

spring.cloud.gateway.server.webflux.routes[14].id=action-docs
spring.cloud.gateway.server.webflux.routes[14].uri=http://localhost:1012
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/mst-action-api-docs,/mst-action-api-docs/**

spring.cloud.gateway.server.webflux.routes[15].id=processor-docs
spring.cloud.gateway.server.webflux.routes[15].uri=http://localhost:1013
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/mst-processor-api-docs,/mst-processor-api-docs/**

spring.cloud.gateway.server.webflux.routes[16].id=email-docs
spring.cloud.gateway.server.webflux.routes[16].uri=http://localhost:1014
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/mst-email-api-docs,/mst-email-api-docs/**

spring.cloud.gateway.server.webflux.routes[17].id=sms-docs
spring.cloud.gateway.server.webflux.routes[17].uri=http://localhost:1015
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/mst-sms-api-docs,/mst-sms-api-docs/**

spring.cloud.gateway.server.webflux.routes[18].id=logger-docs
spring.cloud.gateway.server.webflux.routes[18].uri=http://localhost:1016
spring.cloud.gateway.server.webflux.routes[18].predicates[0]=Path=/mst-logger-api-docs,/mst-logger-api-docs/**

spring.cloud.gateway.server.webflux.routes[19].id=evaluation-docs
spring.cloud.gateway.server.webflux.routes[19].uri=http://localhost:1017
spring.cloud.gateway.server.webflux.routes[19].predicates[0]=Path=/mst-evaluation-api-docs,/mst-evaluation-api-docs/**