apiVersion: v1
kind: Service
metadata:
  name: processor-ms
  namespace: alerthub
spec:
  type: ClusterIP
  selector:
    app: processor-ms
  ports:
  - name: http
    port: 1013
    targetPort: 1013
