spring.application.name=EvaluationMS
server.port=1017

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# Other services
loader.service.url=${LOADER_URL:http://localhost:1010/api/loader}

# Default email recipient for evaluation results
evaluation.notification.to=${EVALUATION_NOTIFICATION_TO:aymanw199816@hotmail.com}

# Swagger
springdoc.swagger-ui.path=/mst-evaluation-sw-ui
springdoc.api-docs.path=/mst-evaluation-api-docs
springdoc.swagger-ui.tryItOutEnabled=false