apiVersion: v1
kind: Secret
metadata:
  name: alerthub-secrets
  namespace: alerthub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
  JWT_SECRET: AlertHubSecuritySecretKey19981998
  SPRING_MAIL_USERNAME: aebayw@gmail.com
  SPRING_MAIL_PASSWORD: gntddryfsdymjuki
  TWILIO_API_KEY: SK993a060ddc73ff95c294e6af7dbb6a7d
  TWILIO_API_SECRET: Vy0uq3aIgAtM775EoDNmVTDqrV5lIROV
  TWILIO_ACCOUNT_SID: ACd829e75909b477dd95ba129fb4e26803
  TWILIO_MESSAGING_SERVICE_SID: MGcc98a1bdbdcba3378720b6ee15c9facc
