@echo off
kubectl apply -f 00-namespace.yaml
kubectl apply -f 00-secrets.yaml
kubectl apply -f _infra\redis.service.yaml
kubectl apply -f _infra\redis.deployment.yaml
kubectl apply -f _infra\kafka.service.yaml
kubectl apply -f _infra\kafka.deployment.yaml
kubectl apply -f user-ms\user-db.service.yaml
kubectl apply -f user-ms\user-db.StatefulSet.yaml
kubectl apply -f loader-ms\loader-db.service.yaml
kubectl apply -f loader-ms\loader-db.StatefulSet.yaml
kubectl apply -f metric-ms\metric-db.service.yaml
kubectl apply -f metric-ms\metric-db.StatefulSet.yaml
kubectl apply -f action-ms\action-db.service.yaml
kubectl apply -f action-ms\action-db.StatefulSet.yaml
kubectl apply -f logger-ms\logger-db.service.yaml
kubectl apply -f logger-ms\logger-db.StatefulSet.yaml
kubectl apply -f user-ms\user-ms.service.yaml
kubectl apply -f user-ms\user-ms.deployment.yaml
kubectl apply -f loader-ms\loader-ms.service.yaml
kubectl apply -f loader-ms\loader-ms.deployment.yaml
kubectl apply -f metric-ms\metric-ms.service.yaml
kubectl apply -f metric-ms\metric-ms.deployment.yaml
kubectl apply -f logger-ms\logger-ms.service.yaml
kubectl apply -f logger-ms\logger-ms.deployment.yaml
kubectl apply -f security-ms\security-ms.service.yaml
kubectl apply -f security-ms\security-ms.deployment.yaml
kubectl apply -f action-ms\action-ms.service.yaml
kubectl apply -f action-ms\action-ms.deployment.yaml
kubectl apply -f processor-ms\processor-ms.service.yaml
kubectl apply -f processor-ms\processor-ms.deployment.yaml
kubectl apply -f email-ms\email-ms.service.yaml
kubectl apply -f email-ms\email-ms.deployment.yaml
kubectl apply -f sms-ms\sms-ms.service.yaml
kubectl apply -f sms-ms\sms-ms.deployment.yaml
kubectl apply -f evaluation-ms\evaluation-ms.service.yaml
kubectl apply -f evaluation-ms\evaluation-ms.deployment.yaml
kubectl apply -f gateway-ms\gateway-ms.service.yaml
kubectl apply -f gateway-ms\gateway-ms.deployment.yaml
kubectl get pods -n alerthub
