spring.application.name=MetricMS

server.port=1011

# connection with MySQL DB
spring.datasource.url=${METRIC_DB_URL:jdbc:mysql://localhost:3306/MetricDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# swagger
springdoc.swagger-ui.path=/mst-metric-sw-ui
springdoc.api-docs.path=/mst-metric-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.document-title=Alert Hub - MetricMS

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true

spring.jackson.mapper.accept-case-insensitive-enums=true