spring.application.name=SmsMS

server.port=1015

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# another services
logger.service.url=${LOGGER_URL:http://localhost:1016/api/logger}

# swagger
springdoc.swagger-ui.path=/mst-sms-sw-ui
springdoc.api-docs.path=/mst-sms-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.document-title=Alert Hub - SmsMS

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true

# TWILIO
twilio.api.key=${TWILIO_API_KEY:SK993a060ddc73ff95c294e6af7dbb6a7d}
twilio.api.secret=${TWILIO_API_SECRET:Vy0uq3aIgAtM775EoDNmVTDqrV5lIROV}
twilio.account.sid=${TWILIO_ACCOUNT_SID:ACd829e75909b477dd95ba129fb4e26803}
twilio.messaging.service.sid=${TWILIO_MESSAGING_SERVICE_SID:MGcc98a1bdbdcba3378720b6ee15c9facc}
