spring.application.name=SmsMS

server.port=1015

spring.kafka.bootstrap-servers=localhost:9092



# another services
logger.service.url=http://localhost:1016/api/logger


#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-sms-sw-ui
# -YAML
springdoc.api-docs.path=/mst-sms-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=false


# TWILIO
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.messaging.service.sid=${TWILIO_MESSAGING_SERVICE_SID}