spring.application.name=SmsMS

server.port=1015

spring.kafka.bootstrap-servers=localhost:9092



# another services
logger.service.url=http://localhost:1016/api/logger


#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-sms-sw-ui
# -YAML
springdoc.api-docs.path=/mst-sms-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=true
#Change title web
springdoc.swagger-ui.document-title=Alert Hub - SmsMS

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true
# TWILIO
twilio.account.sid=ACd829e75909b477dd95ba129fb4e26803
twilio.auth.token=8d243ca53d497e28bf78c3de7b545c87
twilio.messaging.service.sid=MGcc98a1bdbdcba3378720b6ee15c9facc


# option 2 - add .env file
# spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# twilio.account.sid=${TWILIO_ACCOUNT_SID}
# twilio.auth.token=${TWILIO_AUTH_TOKEN}
# twilio.messaging.service.sid=${TWILIO_MESSAGING_SERVICE_SID}