spring.application.name=ProcessorMS

server.port=2000

spring.kafka.bootstrap-servers=localhost:9092



# another services
loader.service.url = http://localhost:1000/api/loader
metric.service.url = http://localhost:3000/api/meric


#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-processor-sw-ui
# -YAML
springdoc.api-docs.path=/mst-processor-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=false

spring.jackson.mapper.accept-case-insensitive-enums=true
