spring.application.name=ProcessorMS

server.port=1013

spring.kafka.bootstrap-servers=localhost:9092



# another services
loader.service.url=http://localhost:1010/api/loader
metric.service.url=http://localhost:1011/api/metric
logger.service.url=http://localhost:1016/api/logger



#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-processor-sw-ui
# -YAML
springdoc.api-docs.path=/mst-processor-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=false
