spring.application.name=EmailMS

server.port=1014

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# another services
logger.service.url=${LOGGER_URL:http://localhost:1016/api/logger}

# swagger
springdoc.swagger-ui.path=/mst-email-sw-ui
springdoc.api-docs.path=/mst-email-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.document-title=Alert Hub - EmailMS
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.deepLinking=true

# send email
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:aebayw@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:gntddryfsdymjuki}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true