spring.application.name=LoggerMS

server.port=1016

# connection with MongoDB
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=logger
#for swagger
# - swagger-ui
springdoc.swagger-ui.path=/mst-metric-sw-ui
# -YAML
springdoc.api-docs.path=/mst-metric-api-docs
#-TryOut
springdoc.swagger-ui.tryItOutEnabled=false
